language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install:
- export TZ=Pacific/Noumea
install: mvn install checksum:files -DskipTests=true -Dmaven.javadoc.skip=true -B -V
notifications:
  slack: 
    rooms:
      secure: "cX4csYKQt1dmhudVVDPSPg7GaoxQ/Bl0UsOXbyuUqY7YL/wg10JHRc2nW4S/fqdcKWL3IlZIFxbK9E03PKrLHIqA7ZJthKEvxwGCdMB6z7J08ztSQMGsi3XRd7pMHz7H49dVDZc7IpiAuyUROkG/Fi3IxMMBzIb65uC2WKAEJnNP1xPRAHd4NDtzZI0UsWUoLH2fdvaJOJpY2aLiUF5NKth1QJrSYfGDVH5H8vfsbjiBLPiHEJYWOzW/yjcQpi32AkrQD2DDXYOIvnKJbbrtk/OI87yQSE/k1fUqa6OL41ZmHmwKQimGo02ybNvkksgTYL65zbZjWTQ5dOjmMaJ1OPXmfaXLxooW1cdOIW54voHWzXNO7n/695Lo/ElSZ2gDPf6WmXNijasMuYkAFVAdSQIABMXnYFSoaFktWn5IqSH7glrSxFaZTTI3F18BG50oq8Z31KtazhTUkTcX2FHZPXmR/rUgIDA7zGGPbLcPlSl0s6OziorOUCBmzohhkVrsiuEoQohDvVNpUbCOKiqeTGlaNGiuXOMAZ++Cbe7qXbtbspb7bIrvrBPZ1JB0cDPrJZIPlVeVjenJA2XAe9c21vqAXstvma0ugTiexmKdwWI+xYjs3G3aIMOdgsO7yqQu8ihcsyEeupKJy17Cd8NvYopOaLTBZw9imxti+qmqwRU="