language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install:
- export TZ=Pacific/Noumea
install: mvn install checksum:files -DskipTests=true -Dmaven.javadoc.skip=true -B -V
notifications:
  slack:
    rooms:
      secure: cX4csYKQt1dmhudVVDPSPg7GaoxQ/Bl0UsOXbyuUqY7YL/wg10JHRc2nW4S/fqdcKWL3IlZIFxbK9E03PKrLHIqA7ZJthKEvxwGCdMB6z7J08ztSQMGsi3XRd7pMHz7H49dVDZc7IpiAuyUROkG/Fi3IxMMBzIb65uC2WKAEJnNP1xPRAHd4NDtzZI0UsWUoLH2fdvaJOJpY2aLiUF5NKth1QJrSYfGDVH5H8vfsbjiBLPiHEJYWOzW/yjcQpi32AkrQD2DDXYOIvnKJbbrtk/OI87yQSE/k1fUqa6OL41ZmHmwKQimGo02ybNvkksgTYL65zbZjWTQ5dOjmMaJ1OPXmfaXLxooW1cdOIW54voHWzXNO7n/695Lo/ElSZ2gDPf6WmXNijasMuYkAFVAdSQIABMXnYFSoaFktWn5IqSH7glrSxFaZTTI3F18BG50oq8Z31KtazhTUkTcX2FHZPXmR/rUgIDA7zGGPbLcPlSl0s6OziorOUCBmzohhkVrsiuEoQohDvVNpUbCOKiqeTGlaNGiuXOMAZ++Cbe7qXbtbspb7bIrvrBPZ1JB0cDPrJZIPlVeVjenJA2XAe9c21vqAXstvma0ugTiexmKdwWI+xYjs3G3aIMOdgsO7yqQu8ihcsyEeupKJy17Cd8NvYopOaLTBZw9imxti+qmqwRU=
before_deploy:
  - export RELEASE_PKG_FILE=$(ls target/*.jar)
  - export RELEASE_PKG_MD5_FILE=$(ls target/*.jar.md5)
  - export RELEASE_PKG_SHA_FILE=$(ls target/*.jar.sha1)
  - echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: oh2WVAMJeKn/iQjlFgeC5615Sz0mpo4ARqUcjqTxtvsCz5KwhLMgdVPqOjFaV6qnu8ZXrrfX9ib4/+REe0T8E/gIwA7V4shifRTDupLN2edCme4uK22UwaICiewJJY1LgThn8DrTgSpW4DHrIGDj0OWT9H1qonxkAlMZ7GN+MLDBSMdBPaQyawtfP+R9eAFLVNLQxdypXb62t81qppeOaoLnQvac8Dry5wkpj54i0+jIPiGLSfhN7Q24T0Ju7e1DrnzcCSvJk9CrxtkgGQC2lddw8S3UYbkkMk5CxzYeesl5QdAW0Z4d9PjHBUcXew0j2E9rmMwSa3G5M/aeFJh47n460XLNBE8VIJEYU9Id8A9C7ksQw3kRXjre/SrugZocYoezFr6uRX4Ni3ORLJaZdBGlzmj07QC4s16bLfquH1WGxPOmAXTnFy2sskHpTyLduMOrcZxHgech10STqVgz/QkI4I1xSLnVtvA1m49llROCxnQ2RD/BZ9kz6WNwCkEZx+E/6qUqa7vfaBUJVEhvbd+syp5PgojF6owCI2Nwmt2+KfoaBfMOGn59dw5E0uXPAYwlJV6kUlDgWJRQCxlxQYHKLUBlMtQQ4amNsvgs31KkBrEhr8f74b3Lv7CHPUGAyL52IOI12klgxD7DOGYxNMISyEpcyeVaa9AB5j4XjMs=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  skip_cleanup: true
  on:
    tags: true
    repo: DSI-Ville-Noumea/batch-migrate-sharepoint-to-alfresco
