language: java
jdk:
- oraclejdk8
cache:
  directories:
  - $HOME/.m2
before_install:
- export TZ=Pacific/Noumea
install: mvn install checksum:files -DskipTests=true -Dmaven.javadoc.skip=true -B -V
notifications:
  slack:
    rooms:
      secure: cX4csYKQt1dmhudVVDPSPg7GaoxQ/Bl0UsOXbyuUqY7YL/wg10JHRc2nW4S/fqdcKWL3IlZIFxbK9E03PKrLHIqA7ZJthKEvxwGCdMB6z7J08ztSQMGsi3XRd7pMHz7H49dVDZc7IpiAuyUROkG/Fi3IxMMBzIb65uC2WKAEJnNP1xPRAHd4NDtzZI0UsWUoLH2fdvaJOJpY2aLiUF5NKth1QJrSYfGDVH5H8vfsbjiBLPiHEJYWOzW/yjcQpi32AkrQD2DDXYOIvnKJbbrtk/OI87yQSE/k1fUqa6OL41ZmHmwKQimGo02ybNvkksgTYL65zbZjWTQ5dOjmMaJ1OPXmfaXLxooW1cdOIW54voHWzXNO7n/695Lo/ElSZ2gDPf6WmXNijasMuYkAFVAdSQIABMXnYFSoaFktWn5IqSH7glrSxFaZTTI3F18BG50oq8Z31KtazhTUkTcX2FHZPXmR/rUgIDA7zGGPbLcPlSl0s6OziorOUCBmzohhkVrsiuEoQohDvVNpUbCOKiqeTGlaNGiuXOMAZ++Cbe7qXbtbspb7bIrvrBPZ1JB0cDPrJZIPlVeVjenJA2XAe9c21vqAXstvma0ugTiexmKdwWI+xYjs3G3aIMOdgsO7yqQu8ihcsyEeupKJy17Cd8NvYopOaLTBZw9imxti+qmqwRU=
before_deploy:
 - export RELEASE_PKG_FILE=$(ls target/*.jar)
 - export RELEASE_PKG_MD5_FILE=$(ls target/*.jar.md5)
 - export RELEASE_PKG_SHA_FILE=$(ls target/*.jar.sha1)
 - echo "deploying $RELEASE_PKG_FILE , $RELEASE_PKG_MD5_FILE , $RELEASE_PKG_SHA_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: opkEMDsjIM2woU0+QOrqaMG/EPK7M6971eXVxVZfxm5crpf2XpHEhkG3TtNu1YG0u7E5qOulyx/aigoxaZzWzP8dPRIOD4iurfG85WLvMtfLaDA4e8V2tu/sfXc15/n/byOj96MQI8qIXOagN1AtypExYN4Np4cVz0VHExXEYs0OH5bq8QGA4CefS1D7ehhA/+E4UIthFO7CP2D7bplEPXmI9KX8SgSzy/1a5VYmdGPC06x2ZSJGf/tZ4mlQRaKew3VoSUMjivbNysVw5AQ1xiWx8ezXjf6DjfZd19xDR022XREKc5za6W0qhxStIM729JlWfm+iu2asJBNWw6UHQMs+xRiKonAm0nYgh35sSzo/mso/FnNNDGWkzB1v/sDwjfGh4sYpMMCP3WG98xAmVTU5J8Mw4KXYCtF7TgTwSJ3KgSP9LXA5Nn7K5fZ36maMtYwsIYy4Q8QO5alWbUFzLMMO/zzWKsXBII6mjsBe2yPWkR54B1Z8SZmI2DFN2DpGl4Ycy5emxwJfYsFgSUr1TSrsq2IETJtfFIoiRvHbI1MDce/wFoJEwy1DaqvflaOZHWd3STCdkDGMNhzedIhcMVJRSnjAXYsMlATU7Y6pzt18oOfTyDXny9hnYwbJ5uWvkFEAN9OmrP1S8dUWfWMbhxCjjR8FEPoHJ+gQXMzdCxk=
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_PKG_MD5_FILE}"
  - "${RELEASE_PKG_SHA_FILE}"
  skip_cleanup: true
  on:
   tags: true
   repo: DSI-Ville-Noumea/batch-migrate-sharepoint-to-alfresco
